export const themes = [
  {
    id: "sunshine",
    name: "Sunshine",
    emoji: "☀️",
    colors: {
      primary: "#FFD166",
      secondary: "#06D6A0",
      accent: "#EF476F",
      background: "#FFFDF7",
      surface: "#FFFFFF",
      textPrimary: "#2B2D42",
      textSecondary: "#555B6E",
    },
  },
  {
    id: "night-owl",
    name: "Night Owl",
    emoji: "🌙",
    colors: {
      primary: "#BB86FC",
      secondary: "#03DAC6",
      accent: "#FF6B6B",
      background: "#121212",
      surface: "#1E1E2E",
      textPrimary: "#E0E0E0",
      textSecondary: "#A0A0B0",
    },
  },
  {
    id: "ocean",
    name: "Ocean Breeze",
    emoji: "🌊",
    colors: {
      primary: "#0077B6",
      secondary: "#00B4D8",
      accent: "#FF9F1C",
      background: "#F0F8FF",
      surface: "#FFFFFF",
      textPrimary: "#023047",
      textSecondary: "#3D5A80",
    },
  },
  {
    id: "blossom",
    name: "Blossom Garden",
    emoji: "🌸",
    colors: {
      primary: "#E63946",
      secondary: "#F4A261",
      accent: "#2A9D8F",
      background: "#FFF0F3",
      surface: "#FFFFFF",
      textPrimary: "#3D0814",
      textSecondary: "#6B2737",
    },
  },
  {
    id: "nature",
    name: "Nature Forest",
    emoji: "🌿",
    colors: {
      primary: "#2D6A4F",
      secondary: "#95D5B2",
      accent: "#FFBA08",
      background: "#F1FAEE",
      surface: "#FFFFFF",
      textPrimary: "#1B4332",
      textSecondary: "#40916C",
    },
  },
  {
    id: "candy",
    name: "Candy Pop",
    emoji: "🍬",
    colors: {
      primary: "#9B5DE5",
      secondary: "#F15BB5",
      accent: "#00F5D4",
      background: "#FEF9FF",
      surface: "#FFFFFF",
      textPrimary: "#3A0CA3",
      textSecondary: "#7B2CBF",
    },
  },
];